[[plugins]]
  package = "@netlify/plugin-local-install-core"
[[plugins]]
  package = "netlify-plugin-minify-html"
  [plugins.inputs]
    contexts = [
      'production',
      'branch-deploy',
      'deploy-preview'
    ]
  [plugins.inputs.minifierOptions]
  removeComments = true
  minifyCSS = true
  minifyJS = true
  collapseInlineTagWhitespace = true
  collapseWhitespace=true
